version: "3.6"
services:
  sever_web:
    image: nginx
    ports:
      - "1200:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - desafio
  server_php_fpm:
    build: .
    volumes:
      - ./:/var/www
    networks:
      - desafio
  db_postgres_sql:
    image: postgres:12
    tty: true
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=desafio_db
      - PGDATA=/var/lib/postgresql/data/db-files/
    networks:
      - desafio
volumes:
  postgres_data:
    driver: local

networks:
  desafio:
    name: desafio
    driver: bridge